package aws

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/cloudbooster-io/cbx-cli/internal/audit/parsers"
)

// TestDescriberFieldManifestInSync is the CI-sync gate for the
// generated describer-field manifest (parsers.DescriberFieldManifest):
// it re-derives the cb_describer_* key set from THIS package's
// non-test sources (every describer, native lister, and cross-ref
// pass) and fails when the manifest has drifted. The manifest backs
// the LLM-CB-RULES-AHEAD handshake — a rulepack rule whose
// requires_fields name keys this engine never emits stays inert via
// the prose's skip-when-absent discipline, and the manifest makes that
// check mechanical (plan §B.4).
//
// Regenerate after adding/removing a describer field:
//
//	CBX_UPDATE_FIELDS_MANIFEST=1 go test ./internal/audit/discover/aws -run TestDescriberFieldManifestInSync
//
// The manifest lives in internal/audit/parsers (NOT here, where the
// plan first sketched it): discover/aws imports internal/audit, so the
// analyzer could never import a manifest from this package — parsers
// is the shared substrate both sides already import (the same reason
// CBDescriberPrimitiveResolved lives there).
func TestDescriberFieldManifestInSync(t *testing.T) {
	derived := deriveDescriberFields(t)

	if os.Getenv("CBX_UPDATE_FIELDS_MANIFEST") == "1" {
		writeFieldsManifest(t, derived)
	}

	manifest := map[string]bool{}
	for _, f := range parsers.DescriberFieldManifest {
		manifest[f] = true
	}
	derivedSet := map[string]bool{}
	for _, f := range derived {
		derivedSet[f] = true
	}

	var missing, extra []string
	for _, f := range derived {
		if !manifest[f] {
			missing = append(missing, f)
		}
	}
	for _, f := range parsers.DescriberFieldManifest {
		if !derivedSet[f] {
			extra = append(extra, f)
		}
	}
	if len(missing) > 0 || len(extra) > 0 {
		t.Fatalf("parsers.DescriberFieldManifest is out of sync with the discover/aws sources:\n  missing from manifest: %v\n  stale in manifest: %v\nRegenerate: CBX_UPDATE_FIELDS_MANIFEST=1 go test ./internal/audit/discover/aws -run TestDescriberFieldManifestInSync", missing, extra)
	}
	if !sort.StringsAreSorted(parsers.DescriberFieldManifest) {
		t.Fatal("parsers.DescriberFieldManifest is not sorted")
	}
}

var describerFieldPattern = regexp.MustCompile(`^cb_describer_[a-z0-9_]+$`)

// deriveDescriberFields AST-scans every non-test file in this package
// for string literals shaped like a describer key. Literal-exact by
// construction: there is no concatenation-built cb_describer_* key in
// this package (a key only readable by joining strings would defeat
// the prompt's skip-when-absent discipline anyway).
func deriveDescriberFields(t *testing.T) []string {
	t.Helper()
	entries, err := os.ReadDir(".")
	if err != nil {
		t.Fatalf("read package dir: %v", err)
	}

	seen := map[string]bool{
		// Set via the parsers constant (describer_rds.go), so the literal
		// lives in the parsers package, not here.
		parsers.CBDescriberPrimitiveResolved: true,
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, name, nil, 0)
		if err != nil {
			t.Fatalf("parse %s: %v", name, err)
		}
		ast.Inspect(f, func(n ast.Node) bool {
			lit, ok := n.(*ast.BasicLit)
			if !ok || lit.Kind != token.STRING {
				return true
			}
			s, err := strconv.Unquote(lit.Value)
			if err != nil {
				return true
			}
			if describerFieldPattern.MatchString(s) {
				seen[s] = true
			}
			return true
		})
	}

	out := make([]string, 0, len(seen))
	for f := range seen {
		out = append(out, f)
	}
	sort.Strings(out)
	if len(out) < 50 {
		t.Fatalf("derived only %d describer fields — the scan is broken, not the manifest", len(out))
	}
	return out
}

func writeFieldsManifest(t *testing.T, fields []string) {
	t.Helper()
	var b bytes.Buffer
	b.WriteString(`// Code generated by TestDescriberFieldManifestInSync (internal/audit/discover/aws); DO NOT EDIT.
// Regenerate: CBX_UPDATE_FIELDS_MANIFEST=1 go test ./internal/audit/discover/aws -run TestDescriberFieldManifestInSync

package parsers

// DescriberFieldManifest is the sorted set of every cb_describer_*
// Inputs key the AWS discovery engine can emit (describers, native
// listers, cross-resource passes). It is the engine half of the
// rulepack compat handshake: a rulepack rule whose requires_fields
// name keys outside this set is AHEAD of this engine — the rule stays
// inert (skip-when-absent prose discipline) and the audit surfaces an
// info-level LLM-CB-RULES-AHEAD finding instead of silently never
// firing. Lives in parsers because both internal/audit (the check) and
// internal/audit/discover/aws (the emitters + the sync test) import
// this package; see CBDescriberPrimitiveResolved above for the same
// pattern.
var DescriberFieldManifest = []string{
`)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%q,\n", f)
	}
	b.WriteString("}\n")
	if err := os.WriteFile(filepath.Join("..", "..", "parsers", "fields_manifest.go"), b.Bytes(), 0o644); err != nil {
		t.Fatalf("write manifest: %v", err)
	}
}
